### ISSUE TITLE
new customer every order

### ISSUE THREAD

**Issue by tgoeminne** [aune-io/magento2-stripe#2]
Hi,

I am testing this and have found it creates a new customer with same email adress everytime I place the order. Should it not just create one customer and then reuse the customer to make a new charge?

I am also running into server errors, do you experience the same problems?

Greets,
Thomas

**Comment by renatocason** [comment]
Hi @tgoeminne,

Every time a Magento customer vault a payment method, on Stripe it appears as a new customer. This has several reasons (how Stripe APIs work, consistency with other core payment method integrations, and others). If it's a deal breaker, you can contribute to the extension or fork it!

Regarding server errors, can you provide some details?

Thanks,
Renato

**Comment by tgoeminne** [comment]
Which log can I check? I am getting the error when try using the vaulted cards

**Comment by tgoeminne** [comment]
I can see the error in console: failed to load resource the server responded with a status of 400 bad request /rest/default/V1/carts/mine/payment-information

This happen when try using the vault, is weird because before it have worked few times, but now it is giving me the 400 error..

**Comment by tgoeminne** [comment]
Also in the backend/admin when you create the order, the cards will not be listed when clicking stored cards. Then the error there will be public hash should be defined.

**Comment by tgoeminne** [comment]
"message": "You can not specify an `idempotency_key` parameter in the body of your request. Instead, use the Idempotency-Key header. See https://stripe.com/docs/api#idempotent_requests for documentation."

**Comment by renatocason** [comment]
Hi @tgoeminne,

Thanks for the update, it seems to be an update to the APIs.
I will remove the idempotency key and pinpoint the API version to avoid that similar things happen in the future.
Updating this when done.

Renato

**Comment by renatocason** [comment]
Hi @tgoeminne,

New version 1.1.0 is now available, could you give that a try and see if it fixes your issues?

Thanks,
Renato

**Comment by tgoeminne** [comment]
I am still getting a 400 error bad request when using the vaulted cards. Also still every tuime customer order a new customer is created, normally you should create the customer and then store the customer_id so you can reuse that. Otherwise you are creating new customers every time.

**Comment by tgoeminne** [comment]
As I am testing this, I have found that when you set to Authorize, the vaulted card works, when I set it to authorize and capture the vaulted card gives error bad request.

**Comment by renatocason** [comment]
Hi @tgoeminne,

Thanks for pointing out the issue with vaulted cards, it's now fixed on release 1.1.1.
The reason why a new customer is created on Stripe for each vaulted payment method is explained in my first reply. There are no plans to change the way it works in the short term, but feel free to fork the extension or submit a PR.

Regards,
Renato
