### ISSUE TITLE
wrong cctypes_stripe_mapper mastercard

### ISSUE THREAD

**Issue by gtlt** [aune-io/magento2-stripe#4]
Stripe catch payment but magento order is not created (server error msg is displayed), the user can then retry the payment directly. This behavior is very bad as multiples payments are charged without user notification.
**As a enhancement I would suggest to cancel the stripe payment on server error if possible.**

version: 2.0.0
card type : mastercard (american-express is ok)

exception logs:
`[2017-10-21 11:13:59] main.CRITICAL: Notice: Undefined index: mastercard in /var/www/xxx/vendor/aune-io/magento2-stripe/Gateway/Response/VaultDetailsHandler.php on line 147 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: mastercard in /var/www/xxx/vendor/aune-io/magento2-stripe/Gateway/Response/VaultDetailsHandler.php on line 147 at /var/www/xxx/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

PR made https://github.com/aune-io/magento2-stripe/pull/3

**Comment by renatocason** [comment]
Hi @gtlt,

Thank you for your contribution, I merged it a few days ago and created a new revision 2.0.1.
Handling an automatic cancellation of the transaction at that point is a bit tricky, as the ChargeIdHandler might not have been executed yet - my plan to avoid this kind of problems is to increase test coverage, and add integration tests at some point.

Regards,
Renato
