### ISSUE TITLE
Uncaught Error: Class 'Stripe\\Stripe' not found

### ISSUE THREAD

**Issue by lalitmalav** [aune-io/magento2-stripe#8]
Hi,

I have installed this extension on 2.2.6 version and got the error like this:-

"Fatal Error: 'Uncaught Error: Class 'Stripe\\Stripe' not found in \/app\/code\/Aune\/Stripe\/Model\/Adapter\/StripeAdapter.php:87\nStack trace:\n#0 
/app\/code\/Aune\/Stripe\/Model\/Adapter\/StripeAdapter.php(60): Aune\\Stripe\\Model\\Adapter\\StripeAdapter->setAppInfo('AuneStripeM2', '2.1.0', 'https:\/\/gitbub....')\n#1 \
/app\/code\/Aune\/Stripe\/Model\/Adapter\/StripeAdapter.php(45): Aune\\Stripe\\Model\\Adapter\\StripeAdapter->initCredentials()\n#2 \\/vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php(111): Aune\\Stripe\\Model\\Adapter\\StripeAdapter->__construct(Object(Aune\\Stripe\\Gateway\\Config\\Config), Object(Magento\\Framework\\Module\\ModuleList))\n#3 
\/vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php(66): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject('Aune\\\\Stripe\\\\Mod...', Array)\n#4 \/\/app\/code\/Aune\/Stripe\/Model\/Adapter\/StripeAdapter.php' on line 87"

Could you please help on the same ??

**Comment by tgoeminne** [comment]
Is probably because you are missing this https://github.com/stripe/stripe-php

**Comment by renatocason** [comment]
Hi @lalitmalav ,

Could you please confirm how you installed the extension?
If you used composer, `stripe/stripe-php` should have been installed automatically.

Thanks,
Renato

**Comment by lalitmalav** [comment]
Hi ,

Thanks [tgoeminne ](https://github.com/tgoeminne)and [renatocason ](https://github.com/renatocason)for the support.  yes I was missing https://github.com/stripe/stripe-php.
